SELECT HOUR, COUNT(B.datetime) AS COUNT
    FROM (SELECT LEVEL-1 HOUR
            FROM DUAL
         CONNECT BY LEVEL <= 24) A
LEFT OUTER JOIN animal_outs B
ON A.HOUR = TO_CHAR(B.datetime, 'HH24')
GROUP BY HOUR
ORDER BY HOUR;
